#+AUTHOR: Jeremiah Peschka
#+EMAIL: jeremiah.peschka@gmail.com
#+STARTUP: indent showall
#+OPTIONS: tags:nil
#+TITLE: macOS Setup

* Homebrew

Install [[https://brew.sh][Homebrew]]

#+BEGIN_SRC shell
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#+END_SRC

* ZSH

#+BEGIN_SRC shell
brew install zsh
#+END_SRC

~zplugin~ installation is handled below.

* git

#+BEGIN_SRC shell
brew install git
#+END_SRC

* Clone this repo and set up config files

#+BEGIN_SRC shell
mkdir -p ~/src/peschkaj
cd ~/src/peschkaj/
git clone git@github.com:peschkaj/dotfiles.git
git clone git@github.com:peschkaj/seekrets.git

cd ~/src
git clone git@github.com:raxod502/radian.git

cd ~
rm .zshrc .zshenv

# set up ZSH
ln -s ~/src/radian/shell/zsh/.zshrc ~/.zshrc
ln -s ~/src/peschkaj/dotfiles/zsh/.zshrc.local ~/.zshrc.local


# set up git
ln -s ~/src/radian/git/.gitconfig ~/.gitconfig
ln -s ~/src/radian/git/.gitexclude ~/.gitexclude
ln -s ~/src/peschkaj/dotfiles/git/.gitconfig.local ~/.gitconfig.local
ln -s ~/src/peschkaj/dotfiles/GIT_IGNORE ~/.gitignore_global

# source code formatting FTW
ln -s ~/src/peschkaj/dotfiles/.clang-format ~/.clang-format

# bspwm clone for macOS
ln -s ~/src/peschkaj/dotfiles/chunkwmrc ~/.chunkwmrc
ln -s ~/src/peschkaj/dotfiles/khdrc ~/.khdrc



#+END_SRC

* git-open

Adds the [[https://github.com/paulirish/git-open][git-open]] ZSH plugin. This plugin makes it easy to open a git repo's website from the command line, but in the browser of your choice!

#+BEGIN_SRC
cd ~/.oh-my-zsh/custom/plugins
git clone git@github.com:paulirish/git-open.git
# Reload the shell
. ~/.zshrc
#+END_SRC

* System Tooling

#+BEGIN_SRC shell
brew install wget tree gnutls telnet cmake ncurses ponysay cowsay pkg-config \
             glib autoconf automake libtool graphviz imagemagick qemu protobuf \
             ripgrep coreutils watchexec tree cmark-gfm markdown
brew install ispell --with-lang-en
brew install llvm --with-lldb --with-toolchain

curl https://sh.rustup.rs -sSf | sh
rustup component add rls-preview rust-analysis rust-src

mkdir -p ~/.local/bin
cat <<EOF > ~/.local/bin/rust-update
#!/bin/sh

if [ "$1" = '-h' ] ; then
  echo 'Updates rustc & clippy'
  echo 'It first checks if clippy would compile at currentl nightly and if so, it updates.'
  echo 'Options:'
  echo '-h: This help message'
  echo '-f: Skips the check and just updates'
  exit
fi

set -ex

renice -n 10 -p $$

export CARGO_INCREMENTAL=0
export RUSTFLAGS='-C target-cpu=native'

try_out() {
  export RUSTUP_HOME=$HOME/.rustup-attempt
  test -d $RUSTUP_HOME || (rustup toolchain add nightly && rustup default nightly)
  rustup update
  cargo +nightly install --force clippy
  unset RUSTUP_HOME
  export RUSTUP_HOME
}

[ "$1" = '-f' ] || try_out

rustup update
cargo +nightly install --force clippy
EOF
#+END_SRC

* UI Improvements

** Better Window Management

#+BEGIN_SRC shell
brew install chunkwm khd
#+END_SRC

** Compose Key

Instructions taken from https://github.com/gnarf/osx-compose-key

Install Karabiner-Elements from https://pqrs.org/osx/karabiner/ or...

#+BEGIN_SRC shell
mkdir -p .config/karabiner
cp src/peschkaj/dotfiles/karabiner.json .config/karabiner/karabiner.json

mkdir -p ~/Library/KeyBindings
cp ~/src/peschkaj/dotfiles/DefaultKeyBinding.dict ~/Library/KeyBindings/DefaultKeyBinding.dict

brew install karabiner-elements
#+END_SRC

** Fonts!

*** Source Code Pro

#+BEGIN_SRC shell
cd ~/src
git clone --depth 1 --branch release https://github.com/adobe-fonts/source-code-pro.git
cd source-code-pro/OTF
cp *.otf ~/Library/Fonts
#+END_SRC

*** TODO Fira Code

*Fill this in*

*** TODO Pragmata Pro

*Fill this in*


* Emacs

Set up emacs using the [[https://github.com/railwaycat/homebrew-emacsmacport][railwaycat homebrew port]]:

#+BEGIN_SRC shell
brew install emacs-mac --with-imagemagick --with-modern-icon --with-natural-title-bar
brew install watchexec
#+END_SRC

Now we need to set up additional libraries:

#+BEGIN_SRC shell
# prepare for emacs
git clone git@github.com:peschkaj/corgmacs.git ~/src/peschkaj/corgmacs
ln -s ~/src/peschkaj/corgmacs .emacs.d

# blackout makes it easy to remove a moqde from the mode line
git clone git@github.com:raxod502/blackout.git ~/src/blackout/

# LSP mode, UI, and LSP-haskell
git clone git@github.com:emacs-lsp/lsp-mode.git
git clone git@github.com:emacs-lsp/lsp-ui.git
git clone git@github.com:emacs-lsp/lsp-haskell.git
#+END_SRC

** Notifications

Install [[https://github.com/julienXX/terminal-notifier][terminal-notifier]]

** Calendar sync

This relies on [[https://github.com/asoroa/ical2org.py][ical2orgpy]]

#+BEGIN_SRC shell
pip install ical2orgpy
ln -s ~/src/peschkaj/dotfiles/orgCalSync.sh ~/.local/bin/orgCalSync.sh
#+END_SRC

Use Lingon X to create a scheduled task that downloads every X minutes (30 is
probably a bit aggressive, but whatever. Go for it)

** Choose between radian or spacemacs

*** radian

This is already taken care of above

*** spacemacs

Blah, don't do this. Unless you _really_ want spacemacs

#+BEGIN_SRC shell
# First, check that any existing .emacs.d is out of the way
mv .emacs.d _emacs_d_bak
# Clone spacemacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
# link existing .spacemacs and .spacemacs.d
ln -s ~/.spacemacs /Users/jeremiah/src/peschkaj/dotfiles/.spacemacs
ln -s ~/.spacemacs.d /Users/jeremiah/src/peschkaj/dotfiles/.spacemacs
#+END_SRC

Now start emacs and wait for a long time
* Haskell

** Haskell Platform

Download and install the [[https://www.haskell.org/platform/][Haskell Platform]]

#+BEGIN_SRC shell
cabal update
cabal install apply-refact hlint stylish-haskell hasktags hoogle

ln -s ~/src/peschkaj/dotfiles/ghci ~/.ghci
#+END_SRC

** Stack

Download and install Haskell Stack:

#+BEGIN_SRC shell
curl -sSL https://get.haskellstack.org/ | sh
#+END_SRC

** Haskell IDE Engine

Visit [[https://github.com/alanz/haskell-ide-engine/][Haskell IDE Engine on GitHub]] for more information on this one.

As of <2018-07-10 Tue> this can be installed via the following:

#+BEGIN_SRC shell
cd ~
mkdir -p ~/src
cd src
git clone https://github.com/haskell/haskell-ide-engine --recursive
cd haskell-ide-engine
stack install
#+END_SRC

You should grab a book, this is a lengthy build process.

** Paper Boy

[[https://github.com/2mol/pboy][Paper Boy]] is a tool that attempts to provide better filenames for academic papers.

#+BEGIN_SRC shell
git clone git@github.com/2mol/pboy.git
cd pboy
stack install
#+END_SRC

Once that's set up, we need to configure pboy:

#+BEGIN_SRC shell
cat <<EOF > .pboy.toml
inbox = "Downloads"
library = "Documents/reading/lib"
move = true
EOF
#+END_SRC
