

./.screenlayout/default.sh

setxkbmap -option "ctrl:nocaps,compose:menu,altwin:swap_lalt_lwin"

## Set up Alt_R as mod3, need to clear existing mod1 first
xmodmap -e "clear mod1"
xmodmap -e "add mod1 = Alt_L"
xmodmap -e "add mod1 = Meta_L"
xmodmap -e "add mod3 = Alt_R"

## Disabled until I can get a drive with ext4 set up
# dropbox &

greenclip daemon &

volumeicon &

shutter --min_at_startup &

guake &
